// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskTracker.db;

#nullable disable

namespace TaskTracker.db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskTracker.db.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Имя1",
                            LastName = "Фамилия1",
                            MiddleName = "Отчество1",
                            Role = 2,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Имя2",
                            LastName = "Фамилия2",
                            MiddleName = "Отчество2",
                            Role = 3,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Имя3",
                            LastName = "Фамилия3",
                            MiddleName = "Отчество3",
                            Role = 4,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Имя4",
                            LastName = "Фамилия4",
                            MiddleName = "Отчество4",
                            Role = 1,
                            UserName = "user4"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Имя5",
                            LastName = "Фамилия5",
                            MiddleName = "Отчество5",
                            Role = 2,
                            UserName = "user5"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Имя6",
                            LastName = "Фамилия6",
                            MiddleName = "Отчество6",
                            Role = 3,
                            UserName = "user6"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Имя7",
                            LastName = "Фамилия7",
                            MiddleName = "Отчество7",
                            Role = 4,
                            UserName = "user7"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Имя8",
                            LastName = "Фамилия8",
                            MiddleName = "Отчество8",
                            Role = 1,
                            UserName = "user8"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Имя9",
                            LastName = "Фамилия9",
                            MiddleName = "Отчество9",
                            Role = 2,
                            UserName = "user9"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Имя10",
                            LastName = "Фамилия10",
                            MiddleName = "Отчество10",
                            Role = 3,
                            UserName = "user10"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Имя11",
                            LastName = "Фамилия11",
                            MiddleName = "Отчество11",
                            Role = 4,
                            UserName = "user11"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Имя12",
                            LastName = "Фамилия12",
                            MiddleName = "Отчество12",
                            Role = 1,
                            UserName = "user12"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Имя13",
                            LastName = "Фамилия13",
                            MiddleName = "Отчество13",
                            Role = 2,
                            UserName = "user13"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Имя14",
                            LastName = "Фамилия14",
                            MiddleName = "Отчество14",
                            Role = 3,
                            UserName = "user14"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Имя15",
                            LastName = "Фамилия15",
                            MiddleName = "Отчество15",
                            Role = 4,
                            UserName = "user15"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Имя16",
                            LastName = "Фамилия16",
                            MiddleName = "Отчество16",
                            Role = 1,
                            UserName = "user16"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Имя17",
                            LastName = "Фамилия17",
                            MiddleName = "Отчество17",
                            Role = 2,
                            UserName = "user17"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Имя18",
                            LastName = "Фамилия18",
                            MiddleName = "Отчество18",
                            Role = 3,
                            UserName = "user18"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Имя19",
                            LastName = "Фамилия19",
                            MiddleName = "Отчество19",
                            Role = 4,
                            UserName = "user19"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Имя20",
                            LastName = "Фамилия20",
                            MiddleName = "Отчество20",
                            Role = 1,
                            UserName = "user20"
                        });
                });

            modelBuilder.Entity("TaskTracker.db.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectLeadId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectLeadId");

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Описание проекта 1",
                            Name = "Проект 1",
                            ProjectLeadId = 1,
                            ProjectManagerId = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "Описание проекта 2",
                            Name = "Проект 2",
                            ProjectLeadId = 2,
                            ProjectManagerId = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "Описание проекта 3",
                            Name = "Проект 3",
                            ProjectLeadId = 3,
                            ProjectManagerId = 5
                        },
                        new
                        {
                            Id = 4,
                            Description = "Описание проекта 4",
                            Name = "Проект 4",
                            ProjectLeadId = 4,
                            ProjectManagerId = 6
                        },
                        new
                        {
                            Id = 5,
                            Description = "Описание проекта 5",
                            Name = "Проект 5",
                            ProjectLeadId = 5,
                            ProjectManagerId = 7
                        },
                        new
                        {
                            Id = 6,
                            Description = "Описание проекта 6",
                            Name = "Проект 6",
                            ProjectLeadId = 6,
                            ProjectManagerId = 8
                        },
                        new
                        {
                            Id = 7,
                            Description = "Описание проекта 7",
                            Name = "Проект 7",
                            ProjectLeadId = 7,
                            ProjectManagerId = 9
                        },
                        new
                        {
                            Id = 8,
                            Description = "Описание проекта 8",
                            Name = "Проект 8",
                            ProjectLeadId = 8,
                            ProjectManagerId = 10
                        },
                        new
                        {
                            Id = 9,
                            Description = "Описание проекта 9",
                            Name = "Проект 9",
                            ProjectLeadId = 9,
                            ProjectManagerId = 11
                        },
                        new
                        {
                            Id = 10,
                            Description = "Описание проекта 10",
                            Name = "Проект 10",
                            ProjectLeadId = 10,
                            ProjectManagerId = 12
                        },
                        new
                        {
                            Id = 11,
                            Description = "Описание проекта 11",
                            Name = "Проект 11",
                            ProjectLeadId = 11,
                            ProjectManagerId = 13
                        },
                        new
                        {
                            Id = 12,
                            Description = "Описание проекта 12",
                            Name = "Проект 12",
                            ProjectLeadId = 12,
                            ProjectManagerId = 14
                        },
                        new
                        {
                            Id = 13,
                            Description = "Описание проекта 13",
                            Name = "Проект 13",
                            ProjectLeadId = 13,
                            ProjectManagerId = 15
                        },
                        new
                        {
                            Id = 14,
                            Description = "Описание проекта 14",
                            Name = "Проект 14",
                            ProjectLeadId = 14,
                            ProjectManagerId = 16
                        },
                        new
                        {
                            Id = 15,
                            Description = "Описание проекта 15",
                            Name = "Проект 15",
                            ProjectLeadId = 15,
                            ProjectManagerId = 17
                        },
                        new
                        {
                            Id = 16,
                            Description = "Описание проекта 16",
                            Name = "Проект 16",
                            ProjectLeadId = 16,
                            ProjectManagerId = 18
                        },
                        new
                        {
                            Id = 17,
                            Description = "Описание проекта 17",
                            Name = "Проект 17",
                            ProjectLeadId = 17,
                            ProjectManagerId = 19
                        },
                        new
                        {
                            Id = 18,
                            Description = "Описание проекта 18",
                            Name = "Проект 18",
                            ProjectLeadId = 18,
                            ProjectManagerId = 20
                        },
                        new
                        {
                            Id = 19,
                            Description = "Описание проекта 19",
                            Name = "Проект 19",
                            ProjectLeadId = 19,
                            ProjectManagerId = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Описание проекта 20",
                            Name = "Проект 20",
                            ProjectLeadId = 20,
                            ProjectManagerId = 2
                        });
                });

            modelBuilder.Entity("TaskTracker.db.Models.TaskExecutor", b =>
                {
                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.HasKey("TaskItemId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TaskExecutors");

                    b.HasData(
                        new
                        {
                            TaskItemId = 1,
                            EmployeeId = 1
                        },
                        new
                        {
                            TaskItemId = 1,
                            EmployeeId = 3
                        },
                        new
                        {
                            TaskItemId = 2,
                            EmployeeId = 2
                        },
                        new
                        {
                            TaskItemId = 2,
                            EmployeeId = 4
                        },
                        new
                        {
                            TaskItemId = 3,
                            EmployeeId = 3
                        },
                        new
                        {
                            TaskItemId = 3,
                            EmployeeId = 5
                        },
                        new
                        {
                            TaskItemId = 4,
                            EmployeeId = 4
                        },
                        new
                        {
                            TaskItemId = 4,
                            EmployeeId = 6
                        },
                        new
                        {
                            TaskItemId = 5,
                            EmployeeId = 5
                        },
                        new
                        {
                            TaskItemId = 5,
                            EmployeeId = 7
                        },
                        new
                        {
                            TaskItemId = 6,
                            EmployeeId = 6
                        },
                        new
                        {
                            TaskItemId = 6,
                            EmployeeId = 8
                        },
                        new
                        {
                            TaskItemId = 7,
                            EmployeeId = 7
                        },
                        new
                        {
                            TaskItemId = 7,
                            EmployeeId = 9
                        },
                        new
                        {
                            TaskItemId = 8,
                            EmployeeId = 8
                        },
                        new
                        {
                            TaskItemId = 8,
                            EmployeeId = 10
                        },
                        new
                        {
                            TaskItemId = 9,
                            EmployeeId = 9
                        },
                        new
                        {
                            TaskItemId = 9,
                            EmployeeId = 11
                        },
                        new
                        {
                            TaskItemId = 10,
                            EmployeeId = 10
                        },
                        new
                        {
                            TaskItemId = 10,
                            EmployeeId = 12
                        },
                        new
                        {
                            TaskItemId = 11,
                            EmployeeId = 11
                        },
                        new
                        {
                            TaskItemId = 11,
                            EmployeeId = 13
                        },
                        new
                        {
                            TaskItemId = 12,
                            EmployeeId = 12
                        },
                        new
                        {
                            TaskItemId = 12,
                            EmployeeId = 14
                        },
                        new
                        {
                            TaskItemId = 13,
                            EmployeeId = 13
                        },
                        new
                        {
                            TaskItemId = 13,
                            EmployeeId = 15
                        },
                        new
                        {
                            TaskItemId = 14,
                            EmployeeId = 14
                        },
                        new
                        {
                            TaskItemId = 14,
                            EmployeeId = 16
                        },
                        new
                        {
                            TaskItemId = 15,
                            EmployeeId = 15
                        },
                        new
                        {
                            TaskItemId = 15,
                            EmployeeId = 17
                        },
                        new
                        {
                            TaskItemId = 16,
                            EmployeeId = 16
                        },
                        new
                        {
                            TaskItemId = 16,
                            EmployeeId = 18
                        },
                        new
                        {
                            TaskItemId = 17,
                            EmployeeId = 17
                        },
                        new
                        {
                            TaskItemId = 17,
                            EmployeeId = 19
                        },
                        new
                        {
                            TaskItemId = 18,
                            EmployeeId = 18
                        },
                        new
                        {
                            TaskItemId = 18,
                            EmployeeId = 20
                        },
                        new
                        {
                            TaskItemId = 19,
                            EmployeeId = 19
                        },
                        new
                        {
                            TaskItemId = 19,
                            EmployeeId = 1
                        },
                        new
                        {
                            TaskItemId = 20,
                            EmployeeId = 20
                        },
                        new
                        {
                            TaskItemId = 20,
                            EmployeeId = 2
                        });
                });

            modelBuilder.Entity("TaskTracker.db.Models.TaskGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaskGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Группа задач 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Группа задач 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Группа задач 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Группа задач 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Группа задач 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Группа задач 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Группа задач 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Группа задач 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Группа задач 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Группа задач 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Группа задач 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Группа задач 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Группа задач 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Группа задач 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Группа задач 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Группа задач 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Группа задач 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Группа задач 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Группа задач 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Группа задач 20"
                        });
                });

            modelBuilder.Entity("TaskTracker.db.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TaskGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskGroupId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 1",
                            Priority = 2,
                            ProjectId = 1,
                            Status = 2,
                            TaskGroupId = 1,
                            Title = "Задача 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 2",
                            Priority = 3,
                            ProjectId = 2,
                            Status = 1,
                            TaskGroupId = 2,
                            Title = "Задача 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 3",
                            Priority = 4,
                            ProjectId = 3,
                            Status = 2,
                            TaskGroupId = 3,
                            Title = "Задача 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 4",
                            Priority = 5,
                            ProjectId = 4,
                            Status = 1,
                            TaskGroupId = 4,
                            Title = "Задача 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 5",
                            Priority = 1,
                            ProjectId = 5,
                            Status = 2,
                            TaskGroupId = 5,
                            Title = "Задача 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 6",
                            Priority = 2,
                            ProjectId = 6,
                            Status = 1,
                            TaskGroupId = 6,
                            Title = "Задача 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 7",
                            Priority = 3,
                            ProjectId = 7,
                            Status = 2,
                            TaskGroupId = 7,
                            Title = "Задача 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 8",
                            Priority = 4,
                            ProjectId = 8,
                            Status = 1,
                            TaskGroupId = 8,
                            Title = "Задача 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 9",
                            Priority = 5,
                            ProjectId = 9,
                            Status = 2,
                            TaskGroupId = 9,
                            Title = "Задача 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 10",
                            Priority = 1,
                            ProjectId = 10,
                            Status = 1,
                            TaskGroupId = 10,
                            Title = "Задача 10"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 11",
                            Priority = 2,
                            ProjectId = 11,
                            Status = 2,
                            TaskGroupId = 11,
                            Title = "Задача 11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 12",
                            Priority = 3,
                            ProjectId = 12,
                            Status = 1,
                            TaskGroupId = 12,
                            Title = "Задача 12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 13",
                            Priority = 4,
                            ProjectId = 13,
                            Status = 2,
                            TaskGroupId = 13,
                            Title = "Задача 13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 14",
                            Priority = 5,
                            ProjectId = 14,
                            Status = 1,
                            TaskGroupId = 14,
                            Title = "Задача 14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 15",
                            Priority = 1,
                            ProjectId = 15,
                            Status = 2,
                            TaskGroupId = 15,
                            Title = "Задача 15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 16",
                            Priority = 2,
                            ProjectId = 16,
                            Status = 1,
                            TaskGroupId = 16,
                            Title = "Задача 16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 17",
                            Priority = 3,
                            ProjectId = 17,
                            Status = 2,
                            TaskGroupId = 17,
                            Title = "Задача 17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 18",
                            Priority = 4,
                            ProjectId = 18,
                            Status = 1,
                            TaskGroupId = 18,
                            Title = "Задача 18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 19",
                            Priority = 5,
                            ProjectId = 19,
                            Status = 2,
                            TaskGroupId = 19,
                            Title = "Задача 19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 20",
                            Priority = 1,
                            ProjectId = 20,
                            Status = 1,
                            TaskGroupId = 20,
                            Title = "Задача 20"
                        });
                });

            modelBuilder.Entity("TaskTracker.db.Models.TaskWatcher", b =>
                {
                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.HasKey("TaskItemId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TaskWatchers");

                    b.HasData(
                        new
                        {
                            TaskItemId = 1,
                            EmployeeId = 7
                        },
                        new
                        {
                            TaskItemId = 2,
                            EmployeeId = 8
                        },
                        new
                        {
                            TaskItemId = 3,
                            EmployeeId = 9
                        },
                        new
                        {
                            TaskItemId = 4,
                            EmployeeId = 10
                        },
                        new
                        {
                            TaskItemId = 5,
                            EmployeeId = 11
                        },
                        new
                        {
                            TaskItemId = 6,
                            EmployeeId = 12
                        },
                        new
                        {
                            TaskItemId = 7,
                            EmployeeId = 13
                        },
                        new
                        {
                            TaskItemId = 8,
                            EmployeeId = 14
                        },
                        new
                        {
                            TaskItemId = 9,
                            EmployeeId = 15
                        },
                        new
                        {
                            TaskItemId = 10,
                            EmployeeId = 16
                        },
                        new
                        {
                            TaskItemId = 11,
                            EmployeeId = 17
                        },
                        new
                        {
                            TaskItemId = 12,
                            EmployeeId = 18
                        },
                        new
                        {
                            TaskItemId = 13,
                            EmployeeId = 19
                        },
                        new
                        {
                            TaskItemId = 14,
                            EmployeeId = 20
                        },
                        new
                        {
                            TaskItemId = 15,
                            EmployeeId = 1
                        },
                        new
                        {
                            TaskItemId = 16,
                            EmployeeId = 2
                        },
                        new
                        {
                            TaskItemId = 17,
                            EmployeeId = 3
                        },
                        new
                        {
                            TaskItemId = 18,
                            EmployeeId = 4
                        },
                        new
                        {
                            TaskItemId = 19,
                            EmployeeId = 5
                        },
                        new
                        {
                            TaskItemId = 20,
                            EmployeeId = 6
                        });
                });

            modelBuilder.Entity("TaskTracker.db.Models.Project", b =>
                {
                    b.HasOne("TaskTracker.db.Models.Employee", "ProjectLead")
                        .WithMany()
                        .HasForeignKey("ProjectLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTracker.db.Models.Employee", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectLead");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("TaskTracker.db.Models.TaskExecutor", b =>
                {
                    b.HasOne("TaskTracker.db.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTracker.db.Models.TaskItem", "TaskItem")
                        .WithMany("Executors")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskTracker.db.Models.TaskItem", b =>
                {
                    b.HasOne("TaskTracker.db.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTracker.db.Models.TaskGroup", "TaskGroup")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("TaskGroup");
                });

            modelBuilder.Entity("TaskTracker.db.Models.TaskWatcher", b =>
                {
                    b.HasOne("TaskTracker.db.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTracker.db.Models.TaskItem", "TaskItem")
                        .WithMany("Watchers")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskTracker.db.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskTracker.db.Models.TaskGroup", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskTracker.db.Models.TaskItem", b =>
                {
                    b.Navigation("Executors");

                    b.Navigation("Watchers");
                });
#pragma warning restore 612, 618
        }
    }
}
